deployments:
  - name: development
    on_push: true
    on_push_branch: development

  - name: staging
    on_push: true
    on_push_branch: staging

  - name: production
    on_push: true
    on_push_branch: main
