name: Runs ESLint & Tests
'on':
  pull_request:
    types:
      - opened
      - ready_for_review
      - edited
      - synchronize
concurrency:
  group: 'test-${{ github.workflow }}-${{ github.head_ref || github.run_id }}-${{ github.ref }}'
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set node Version
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install Modules
        run: yarn install --frozen-lockfile
      - name: Run ESLint
        run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set node Version
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install Modules
        run: yarn install --frozen-lockfile
      - name: Run Vitest
        run: yarn test
