name: Runs ESLint & Tests

on:
  pull_request:
    types: [ opened, ready_for_review, edited, synchronize ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set node Version
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install Modules
        run: npm i

      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set node Version
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install Modules
        run: npm i

      - name: Run Vitest
        run: npm run test

