name: Deploy - Production

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write
concurrency:
  group: 'deploy-${{ github.workflow }}-${{ github.head_ref || github.run_id }}-${{ github.ref }}'
  cancel-in-progress: true
jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/base-deploy.yaml
    with:
      ENVIRONMENT: 'production'
      SHA: '${{ github.sha }}'
    secrets:
      PAGE_URL: '${{secrets.PAGE_URL}}'
      CLOUD_URL: 'https://developer.europe-west1.gcp.storefrontcloud.io'
      CLOUD_INSTANCE: 'https://farmer.storefrontcloud.io/instance/developer-europe-west1-gcp-storefrontcloud-io'
      CLOUD_USERNAME: '${{secrets.CLOUD_USERNAME}}'
      CLOUD_PASSWORD: '${{secrets.CLOUD_PASSWORD}}'
      ALGOLIA_ID: '${{secrets.ALGOLIA_ID}}'
      ALGOLIA_TOKEN: '${{secrets.ALGOLIA_TOKEN}}'
      DEVTO_API_TOKEN: '${{secrets.DEVTO_API_TOKEN}}'
      GITHUB_API_TOKEN: '${{secrets.GITHUB_API_TOKEN}}'
      GOOGLE_TAG_ID: '${{secrets.GOOGLE_TAG_ID}}'
      SLACK_FOOTER: '${{secrets.SLACK_FOOTER}}'
      SLACK_ICON: '${{secrets.SLACK_ICON}}'
      SLACK_USERNAME: '${{secrets.SLACK_USERNAME}}'
      SLACK_WEBHOOK: '${{secrets.SLACK_WEBHOOK}}'
      SUPABASE_URL: '${{secrets.SUPABASE_URL}}'
      SUPABASE_PUBLIC_KEY: '${{secrets.SUPABASE_PUBLIC_KEY}}'
      SUPABASE_SERVICE_ROLE_KEY: '${{secrets.SUPABASE_SERVICE_ROLE_KEY}}'
      DISCORD_TOKEN: '${{secrets.DISCORD_TOKEN}}'
      DISCORD_GUILD_ID: '${{secrets.DISCORD_GUILD_ID}}'
      SENDGRID_API_KEY: '${{secrets.SENDGRID_API_KEY}}'
