name: Deploy - Staging

on:
  push:
    branches:
      - staging

permissions:
  contents: read
  deployments: write
concurrency:
  group: 'deploy-${{ github.workflow }}-${{ github.head_ref || github.run_id }}-${{ github.ref }}'
  cancel-in-progress: true
jobs:
  deploy:
    if: github.ref == 'refs/heads/staging'
    uses: ./.github/workflows/base-deploy.yaml
    with:
      ENVIRONMENT: 'staging'
      SHA: '${{ github.sha }}'
    secrets:
      CLOUD_URL: 'https://developer-test.europe-west1.gcp.storefrontcloud.io'
      CLOUD_INSTANCE: 'https://farmer.storefrontcloud.io/instance/developer-test-europe-west1-gcp-storefrontcloud-io'
      CLOUD_USERNAME: '${{secrets.CLOUD_USERNAME}}'
      CLOUD_PASSWORD: '${{secrets.CLOUD_PASSWORD}}'
      ALGOLIA_ID: '${{secrets.ALGOLIA_ID}}'
      ALGOLIA_TOKEN: '${{secrets.ALGOLIA_TOKEN}}'
      DEVTO_API_TOKEN: '${{secrets.DEVTO_API_TOKEN}}'
      GITHUB_API_TOKEN: '${{secrets.GITHUB_API_TOKEN}}'
      GOOGLE_TAG_ID: '${{secrets.GOOGLE_TAG_ID}}'
      SLACK_FOOTER: '${{secrets.SLACK_FOOTER}}'
      SLACK_ICON: '${{secrets.SLACK_ICON}}'
      SLACK_USERNAME: '${{secrets.SLACK_USERNAME}}'
      SLACK_WEBHOOK: '${{secrets.SLACK_WEBHOOK}}'
