name: Deploy - Development

on:
  push:
    branches:
      - development

permissions:
  contents: read
  deployments: write
concurrency:
  group: 'deploy-${{ github.workflow }}-${{ github.head_ref || github.run_id }}-${{ github.ref }}'
  cancel-in-progress: true
jobs:
  deploy:
    if: github.ref == 'refs/heads/development'
    uses: ./.github/workflows/base-deploy.yaml
    with:
      ENVIRONMENT: 'development'
      SHA: '${{ github.sha }}'
    secrets: inherit
