name: Deploy to Vue Storefront Cloud
on:
  push:
    branches:
      - main
      - beta
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build and publish docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: developer-storefrontcloud-io/vue-storefront:${{ github.sha }}
          registry: registry.vuestorefront.cloud
          username: ${{ secrets.CLOUD_USERNAME }}
          password: ${{ secrets.CLOUD_PASSWORD }}
          dockerfile: .vuestorefrontcloud/docker/Dockerfile
          buildoptions: --compress

  deploy_production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: ${{ github.token }}
          target_url: https://developer.europe-west1.gcp.storefrontcloud.io
          environment: production
          initial_status: in_progress
      - name: Deploy on developer.europe-west1.gcp.storefrontcloud.io
        run: |
          OUTPUT=$(curl -s -H 'X-User-Id: ${{ secrets.CLOUD_USERNAME }}'  -H 'X-Api-Key: ${{ secrets.CLOUD_PASSWORD }}' -H 'Content-Type: application/json' -X PATCH -d '{
              "front_version":"${{ github.sha }}"
            }' https://farmer.storefrontcloud.io/instance/developer-europe-west1-gcp-storefrontcloud-io)
          if echo $OUTPUT | grep -q '"code":200,'; then
            echo "Instance updated"
          else
            echo "Something went wrong during the update process... Response: $OUTPUT"
            exit 1
          fi
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ github.token }}
          target_url: https://developer.europe-west1.gcp.storefrontcloud.io
          state: success
          description: Congratulations! The deploy is done.
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ github.token }}
          target_url: https://developer.europe-west1.gcp.storefrontcloud.io
          description: Unfortunately, the instance hasn't been updated.
          state: failure
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
